[env:rpipicow]
platform  = https://github.com/maxgerhardt/platform-raspberrypi.git
board     = rpipicow
framework = arduino
board_build.core            = earlephilhower
board_build.filesystem_size = 0.5m

board_build.arduino.earlephilhower.usb_manufacturer = MyStudio
board_build.arduino.earlephilhower.usb_product      = WiiMote MIDI
board_build.arduino.earlephilhower.usb_vid          = 0x1209
board_build.arduino.earlephilhower.usb_pid          = 0x0001

build_flags =
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_IPV4
    -DUSE_TINYUSB

lib_deps =
    fortyseveneffects/MIDI Library@^5.0.2
    bblanchon/ArduinoJson@^7.0.0

monitor_speed = 115200